### ISSUE TITLE
Popover Transient Behaviour

### ISSUE THREAD

**Issue by manngo** [zaferarican/menubarpopoverswiftui2#1]
In your sample code, you include the following comment:

```swift
popover.behavior = .transient // !!! - This does not seem to work in SwiftUI2.0 or macOS BigSur yet
```

I’m not using either SwiftUI2 or Big Sur yet, but I had the same trouble in my current project. I found the following helpful:

```swift
popover.contentViewController?.view.window?.makeKey()
```

Reference: https://medium.com/@jbarmanet/thank-you-for-this-nice-intro-aaron-2c3a2b498066

**Comment by zaferarican** [comment]
Thank you very much! It indeed works.
