### ISSUE TITLE
Show popover once the app opens?

### ISSUE THREAD

**Issue by Yang-Xijie** [zaferarican/menubarpopoverswiftui2#3]
I wonder how to show the popover once the app starts?
Thanks for any hints!

**Comment by Yang-Xijie** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/57952362/128480349-07b42b65-d024-4c8f-bf5c-fead88313264.png">

I tried the functions below, but they don't work.

It seems that `popover.isShown` has changed, but the popover not appears.

I'm using Big Sur 11.4

**Comment by Yang-Xijie** [comment]
Check the whole file -- https://github.com/Yang-Xijie/InputSourceSwitcher/blob/main/InputSourceSwitcher/APP/App.swift

**Comment by zaferarican** [comment]
```
DispatchQueue.main.asyncAfter(deadline: .now() + 1.0, execute: {
            self.showPopover(self)
        })
```
after 
`statusBarItem?.button?.action = #selector(AppDelegate.togglePopover(_:))`
will work.

**Comment by Yang-Xijie** [comment]
Sorry for replying late.

The above codes do work! Thank you very much!

```swift
statusBarItem?.button?.action = #selector(AppDelegate.togglePopover(_:))
// When starting the app, show the popover. If don't do like this, open the app and shortcuts will not work until click the icon on the menu bar.
DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
    if let button = self.statusBarItem?.button {
        self.popover.show(
            relativeTo: button.bounds,
            of: button, preferredEdge: NSRectEdge.minY)
    }
}
```

However, the **new issue** is that if the user hide the menu bar (`System Preferences -> Dock & Menu Bar -> Dock & Menu Bar -> Automatically hide and show the menu bar -> checked`), the popover will **appear on the top left corner of the screen**, instead of appearing below the menu bar icon. Is there a way to fix this issue?

**Comment by zaferarican** [comment]
Unfortunately, I do not have a solution for that. Please let me know if you find one.
